#!/bin/bash
# ---------------------------------------------------------------------------
#  Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

if [ "$(uname)" == "Darwin" ]
then
    CURRENT_PATH=$(dirname "$0")
else
    CURRENT_PATH="$(dirname "$(readlink -f "$0")")"
fi

if [ -f "$CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar" ]; then
      echo "ballerina-command-${ballerina.command.version}.jar is already exists hence update failed."
      exit 1
fi

\cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/lib/ballerina-command-${ballerina.command.version}.jar $CURRENT_PATH/../lib || { echo 'copy tool jar failed.' ; exit 1; }
\cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/bin/ballerina $CURRENT_PATH/../bin

if [ $? -ne '0' ]; then
  echo "copy ballerina file failed."
  # remove already copied jar.
  rm -rf $CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar
  exit 1
fi

echo "Updated to latest command version: ${ballerina.command.version}"
echo "Cleaning old files..."

for file in $CURRENT_PATH/../lib/*; do
    if [ -f "$file" ] && [[ "$file" == *ballerina-command*.jar ]] && [[ "$file" != *ballerina-command-${ballerina.command.version}.jar ]]; then
	rm -rf $file
    fi
done
