#!/bin/bash
BALLERINAROOT=/Library/Ballerina
echo "Fixing permissions"
cd $BALLERINAROOT
find . -exec chmod ugo+r \{\} \;
find bin -exec chmod ugo+rx \{\} \;
find . -type d -exec chmod ugo+rx \{\} \;
find lib -exec chmod -R ugo+r \{\} \;
chmod o-w .

rm -f /Library/Ballerina/bin/ballerina
rm -f /etc/paths.d/ballerina
