// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (80, config = {host: "petstore.openapi.io"});

service /v1 on ep0 {
    # List all pets
    #
    # + 'limit - How many items to return at one time (max 100)
    # + return - returns can be any of following types
    # http:Ok (An paged array of pets)
    # http:DefaultStatusCodeResponse (unexpected error)
    resource function get pets(int:Signed32? 'limit) returns Pets|ErrorDefault {
    }
}
