[b7a.users]

[b7a.users.tom]
password="1234"
scopes="subscribe"

[b7a.users.mary]
password="xyz"
scopes="scope2"

[b7a.users.peter]
password="pqr"
scopes="subscribe"

[b7a.users.anne]
password="abc"
scopes="publish"
