[project]
org-name= "bcintegrationtest"
version= "0.1.0"

[dependencies]

 [platform]
 target = "java11"

     [[platform.libraries]]
     artifactId = "utils"
     path = "./utils_lib/utils.jar"
     groupId = "wso2"
     modules = ["utils"]
