name: Publish release

on:
  workflow_dispatch:
    inputs:
      isPreRelease:
        description: 'Tag created is a pre-release tag'
        required: true
        default: 'false'
      preReleaseSuffix:
        description: 'The text that will be suffixed to the Git tag. e.g., rc1'
        required: false
        default: ''

permissions:
  id-token: write
  contents: write

jobs:
  windows-installer-build:
    name: Windows Installer Build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21.0.3'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Install GUID Generator
        run: dotnet tool install -g dotnet-guid --version 0.5.2
      - name: Set up Wix toolkit
        run: echo "${WIX}bin" >> $GITHUB_PATH
        shell: bash
      - name: Set cosign-installer
        uses: sigstore/cosign-installer@v3.5.0
      - name: Download Windows Installer Zip
        run: |
          echo default login ${{ secrets.BALLERINA_BOT_USERNAME }} password ${{ secrets.BALLERINA_BOT_TOKEN }} >> _netrc
          curl --netrc-file _netrc -L -o ballerina-2201.12.7-swan-lake-windows.zip https://github.com/ballerina-platform/ballerina-distribution/releases/download/v2201.12.7/ballerina-2201.12.7-swan-lake-windows.zip
      - name: Create windows-msi Installer
        id: run_installers_msi
        run: |
          move installers\windows .\..\..\
          cd ..\..\windows
          .\build-ballerina-windows-x64.bat --version 2201.12.7-swan-lake --path .\..\ballerina-distribution\ballerina-distribution
          Get-ChildItem -Recurse -File
      - name: Sign the Windows installer
        run: |
          cosign sign-blob D:\a\windows\target\msi\ballerina-2201.12.7-swan-lake-windows-x64.msi --output-certificate ballerina-2201.12.7-swan-lake-windows-x64.msi.pem --output-signature ballerina-2201.12.7-swan-lake-windows-x64.msi.sig --yes
      - name: Verify the Windows installer
        run: |
          cosign verify-blob D:\a\windows\target\msi\ballerina-2201.12.7-swan-lake-windows-x64.msi --certificate ballerina-2201.12.7-swan-lake-windows-x64.msi.pem --signature ballerina-2201.12.7-swan-lake-windows-x64.msi.sig --certificate-identity=https://github.com/ballerina-platform/ballerina-distribution/.github/workflows/publish-release.yml@${{ github.ref }} --certificate-oidc-issuer=https://token.actions.githubusercontent.com
      - name: Generate Hashes
        run: |
          openssl dgst -sha256 -out ballerina-2201.12.7-swan-lake-windows-x64.msi.sha256 D:\a\windows\target\msi\ballerina-*-windows-x64.msi
      
