name: Generate Ballerina By Examples
on:
    push:
        branches:
            - '2201.0.x'
        paths:
            - 'examples/**'
jobs:
    trigger-bbe-gen:
        name: Trigger Ballerina By Examples genration
        if: github.repository_owner == 'ballerina-platform'
        runs-on: ubuntu-latest
        steps:
            -   run: |
                    curl --request \
                    POST 'https://api.github.com/repos/ballerina-platform/ballerina-dev-website/dispatches' \
                    --header 'Accept: application/vnd.github.v3+json' \
                    --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                    --header 'Content-Type: application/json' \
                    --data-raw '{
                        "event_type": "distribution-update"
                    }'
